### ISSUE TITLE
Does it support obfuscated binary?

### ISSUE THREAD

**Issue by febryan-dev** [rscloura/Doldrums#3]
Hello, it's great I discovered Doldrums and it works perfectly.
However, I would like to ask or confirm if doldrums can handle obfuscated binary of flutter app as well, since flutter devs can use --obfuscate flag prior compiling or building the app.

**Comment by rscloura** [comment]
Hi! I have yet to start looking into obfuscated binaries of Flutter/Dart. It might be the case that the obfuscation simply mangles method and class names, in which case Doldrums should still work fine. If it's any more complex than that, it may need some additional support. But currently... I myself don't know!

**Comment by febryan-dev** [comment]
I would like to invite you to my project. Can you come in?

**Comment by rscloura** [comment]
To tackle obfuscated Dart?
